# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
print(x.size)
print(x.itemsize)
print(x.size * x.itemsize)

10
8
80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x00000237AAB6DB80>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
y = np.arange(start=10,stop=49)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
rev = y[::-1]
print(rev)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
re_shape = np.arange(9).reshape(3,3)
print(re_shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
non_zero = [1,2,0,0,4,0]
np.nonzero(non_zero)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
identy_matrix = np.eye(3)
print(identy_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [14]:
random_values = np.random.random((3,3,3))
print(random_values)

[[[0.28353205 0.84464523 0.81714729]
  [0.83836088 0.97753012 0.78580434]
  [0.74688198 0.36651086 0.73290682]]

 [[0.45342606 0.75620865 0.31742331]
  [0.28254719 0.04798065 0.03993006]
  [0.27486896 0.30821291 0.70927541]]

 [[0.39177674 0.64898427 0.78400026]
  [0.39925206 0.63913044 0.84314544]
  [0.96302469 0.52321291 0.3381831 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
random_matrix_array = np.random.rand(10,10)
max_element = np.max(random_matrix_array)
min_element = np.min(random_matrix_array)
print(max_element)
print(min_element)

0.9515682845714786
0.008398374118742447


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [16]:
random_vector = np.random.random(30)
mean_vector = np.mean(random_vector)
mean_vector

0.5012331882973589

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [17]:
border_array = np.ones((5,5))
border_array[1:-1,1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [18]:
border_array = np.pad(border_array, pad_width=1,mode='constant',constant_values=0)
print(border_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [20]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [21]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [22]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [23]:
a= np.array([[1,2],[3,4]])
np.tile(a,(8,8))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [24]:
z = np.random.random((5,5))
zmax, zmin = z.max(),z.min()
z = (z - zmin) / (zmax - zmin)
print(z)

[[0.91169325 0.04583011 1.         0.09385891 0.63559101]
 [0.3944466  0.18073497 0.35376589 0.0720686  0.87521095]
 [0.         0.61268283 0.99019085 0.4716984  0.75102062]
 [0.83500786 0.08834373 0.3806918  0.1174822  0.47005933]
 [0.1467091  0.65338798 0.57576685 0.59984591 0.64069519]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [25]:
color = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

<ipython-input-25-8a679fadaa00>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [26]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x,y)
print(z)

[[1.3803856  0.22704235]
 [0.57430415 0.11139542]
 [0.28919461 0.04322069]
 [1.01515327 0.10827293]
 [1.67802565 0.35038677]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [27]:
arr = np.arange(11)
print(arr)
m = (arr > 3) & (arr < 8)
arr[m] *= -1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(np.sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z = 5
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

3125
16
False
5j
5.0
False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-30-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-30-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [31]:
X = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(X)), X))

[  8.   8.  -3.   3.   5.  10.   2.  -7. -10.  -9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [32]:
arr1 = np.array([1,1,2,3,4])
arr2 = np.array([2,1,4,5])
common_value = np.intersect1d(arr1,arr2)
print(common_value)

[1 2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [33]:
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0
Y = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-34-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [35]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yesterday: ",yesterday)
today = np.datetime64('today','D')
print("Today: ",today)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2021-06-29
Today:  2021-06-30
Tomorrow:  2021-07-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [36]:
print(np.arange('2016-07','2020-06',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' ... '2020-05-29' '2020-05-30'
 '2020-05-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [38]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[1. 2. 5. 2. 8. 8. 0. 3. 3. 1.]
[1. 2. 5. 2. 8. 8. 0. 3. 3. 1.]
[1. 2. 5. 2. 8. 8. 0. 3. 3. 1.]
[1 2 5 2 8 8 0 3 3 1]
[1. 2. 5. 2. 8. 8. 0. 3. 3. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [39]:
X = np.zeros((5,5))
X += np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [40]:
list = np.arange(5)
iterate = iter(list)
x = np.fromiter(iterate,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [41]:
np.linspace(start=0,stop=1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
x = np.random.random(10)
print(x)
x.sort()
print(x)

[0.94407617 0.07544722 0.19369867 0.29180088 0.60579587 0.76175453
 0.16809696 0.65782937 0.08043102 0.12170137]
[0.07544722 0.08043102 0.12170137 0.16809696 0.19369867 0.29180088
 0.60579587 0.65782937 0.76175453 0.94407617]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [43]:
X = np.arange(10)
np.add.reduce(X)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [44]:
x = np.random.randint(0,2,6)
y = np.random.randint(0,2,6)
array_equal = np.allclose(x,y)
print(array_equal)
all_close = np.array_equal(x,y)
print(all_close)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [45]:
a = np.zeros(11)
print(a)
a[1] = 2
print(a)
a.flags.writeable = False
a[1] = 7

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [46]:
x = np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.39893268 0.58500786 0.29240648 1.02091096 1.71421731]
[0.16301791 0.19158687 0.14835387 0.10625504 0.20585117]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [47]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.08795813 0.         0.59897875 0.5842996  0.86156802 0.48058776
 0.62644923 0.59973326 0.49002542 0.64608   ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [48]:
z = np.zeros((5,5) , [('x',float), ('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [49]:
X = np.arange(8)
Y = X + 0.5
Cauchy_matrix = 1/np.subtract.outer(X,Y)
print(np.linalg.det(Cauchy_matrix))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [50]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
-3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
-1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [51]:
import sys
arr = np.arange(31)
np.set_printoptions(threshold=sys.maxsize)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [52]:
X = np.arange(100)
Y = np.random.uniform(0,100)
index = (np.abs(X-Y)).argmin()
print(X[index])

22


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [53]:
x = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color', [('r', float, 1),('g', float, 1),('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-53-3818062619b2>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color', [('r', float, 1),('g', float, 1),('b', float, 1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
z = np.random.random((100,2))
x,y = np.atleast_2d(z[:,0], z[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [55]:
a = np.arange(10, dtype=np.float32)
a = a.astype(np.int32,copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
             6,  ,  , 7, 8\n
             ,  , 9,10,11/n""")
data = np.genfromtxt(s,dtype=[('myint','i8'),('myfloat','f8'),('mystring','S5')], delimiter=",")
data

array([( 1,  2., b' 3'), ( 6, nan, b'  '), (-1, nan, b' 9')],
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', 'S5')])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [57]:
a = np.arange(9).reshape(3,3)
for index ,values in np.ndenumerate(a):
    print(index,values)
#for index in np.ndindex(a.shape):
    #print(index,a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [58]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0,0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [59]:
n = 5
p = 3
out = np.zeros((n,n))
np.put(out,np.random.choice(range(n*n),p,replace=False),1)
out

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [60]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1,keepdims=True)
Y

array([[ 0.42888397,  0.07322481, -0.08364384,  0.37142548,  0.29167431,
        -0.23886107, -0.38152055, -0.30425347, -0.29174325,  0.13481359],
       [ 0.27133288, -0.39816938, -0.09693854,  0.15562491, -0.04131967,
        -0.13877185,  0.2446655 , -0.06908297,  0.33471738, -0.26205826],
       [ 0.3621165 ,  0.13031285, -0.1368009 , -0.09431861, -0.14773158,
        -0.50593238, -0.16008898,  0.13800541,  0.2907725 ,  0.12366518],
       [ 0.22272033,  0.06338575,  0.27917112,  0.15908234, -0.49063274,
        -0.03226127,  0.30408457, -0.40087426, -0.32076114,  0.2160853 ],
       [ 0.06291911,  0.1515615 ,  0.06000941,  0.29153296, -0.30361607,
        -0.17537726, -0.19189626, -0.04776886, -0.04139445,  0.19402991]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [61]:
a = np.random.randint(0,10,(3,3))
print(a[a[:,1].argsort()])

[[9 4 1]
 [5 5 3]
 [0 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [62]:
a = np.random.randint(0,10,(3,3))
print(a)
print((~a.any(axis=0)).any())

[[2 3 0]
 [2 7 3]
 [0 1 8]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [63]:
x = np.random.uniform(1,12,5)
v = 4
n = x.flat[np.abs(x-v).argmin()]
print(n)

3.8674997063889758


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [64]:
a = np.arange(12)
a = a.reshape(3,4)
print(a)
for i in np.nditer(a):
    print(i,end=" ")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [65]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.info = getattr(obj,'name',"no name")

Z = NamedArray(np.arange(5), "range_5")
print(Z.name) 

range_5


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [66]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z)) 
print(Z)

np.add.at(Z,I,1)
print(Z)

[5. 3. 2. 2. 3. 3. 5. 1. 5. 1.]
[9. 5. 3. 3. 5. 5. 9. 1. 9. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [67]:
X = np.arange(1,7)
I = np.arange(1,7)
F = np.bincount(I,X)
print(F)

[0. 1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [68]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*65536 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [69]:
a = np.random.randint(0,10,(4,3,4,3))
sum = a.sum(axis=(-2-1))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[67 54 62]
 [38 37 65]
 [72 54 36]
 [39 51 71]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [70]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S,weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.54479565 0.57472477 0.41956251 0.59866312 0.56785667 0.50139416
 0.53850478 0.52208892 0.55500818 0.86375088]
0    0.544796
1    0.574725
2    0.419563
3    0.598663
4    0.567857
5    0.501394
6    0.538505
7    0.522089
8    0.555008
9    0.863751
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [71]:
a = np.random.rand(10,2)
b = np.random.rand(2,2)
print(np.diag(np.dot(a,b)))
print(a)

[1.1741469  0.37825723]
[[0.71823517 0.64075904]
 [0.67253419 0.50238063]
 [0.8291221  0.56139781]
 [0.96932583 0.71024439]
 [0.76487754 0.52090025]
 [0.89810703 0.5658908 ]
 [0.63926412 0.69345471]
 [0.50614153 0.29405525]
 [0.91253899 0.87212047]
 [0.34069487 0.16857658]]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [72]:
a = np.array([1,2,3,4,5])
p = 3
b = np.zeros(len(a) + (len(a)-1) * (p))
b[::p+1] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [73]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x*y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [74]:
a = np.arange(16).reshape(4,4)
print(a)
a[[0,2]] = a[[2,0]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [75]:
A = np.random.randint(0,100,(10,3))
B = np.roll(A.repeat(2,axis=1), -1,axis=1)
B = B.reshape(len(B)*3,2)
B = np.sort(B,axis=1)
C = B.view(dtype=[('p0',B.dtype),('p1',B.dtype)])
C = np.unique(C)
print(C)

[( 1,  4) ( 1, 20) ( 3, 26) ( 3, 78) ( 4, 10) ( 4, 20) ( 4, 37) (10, 37)
 (11, 69) (11, 83) (14, 42) (14, 43) (18, 65) (18, 73) (20, 40) (20, 82)
 (23, 50) (23, 88) (26, 78) (32, 34) (32, 45) (34, 45) (40, 82) (42, 43)
 (50, 88) (63, 74) (63, 81) (65, 73) (69, 83) (74, 81)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [76]:
C = np.bincount([1,1,2,2,3,3,4])
A = np.repeat(np.arange(len(C)) ,C )
print(A)

[1 1 2 2 3 3 4]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [77]:
def moving_average(a,b):
    test = np.cumsum(a,dtype=float)
    test[b:] = test[b:] - test[:-b]
    return test[n - 1:] / n
moving_average(np.arange(20),5)

array([ 3.125,  3.75 ,  4.375,  5.   ,  5.625,  6.25 ,  6.875,  7.5  ,
        8.125,  8.75 ,  9.375, 10.   , 10.625])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [78]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
X = rolling(np.arange(10),3) 
print(X)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [79]:
A = np.random.randint(0,2,100)
np.logical_not(A, out=A)
A = np.random.uniform(-1.0,1.0,100)
np.negative(A, out=A)

array([ 0.51961626, -0.90530602, -0.29867948,  0.3701838 ,  0.59484535,
       -0.80917677,  0.48418399, -0.16730436,  0.74081426, -0.10738988,
        0.65795091,  0.54628641, -0.65537715,  0.09862991,  0.1250287 ,
        0.69140575, -0.69371769,  0.54060058, -0.58376294,  0.84497749,
       -0.57218326, -0.39909415,  0.88234102, -0.71453975,  0.18244814,
       -0.32333518,  0.76127422, -0.14281624, -0.84355799, -0.19451626,
        0.66189178, -0.71808514, -0.07461873,  0.03449775,  0.59356815,
        0.48005351, -0.95236442, -0.10792589, -0.16814258,  0.87868375,
        0.22282955, -0.23714837,  0.62927041, -0.48159146, -0.34767967,
        0.82568192,  0.84446159,  0.87091823,  0.74861256,  0.09695233,
        0.36218175,  0.32524531,  0.34058418, -0.60081579, -0.3452551 ,
       -0.13651952,  0.35721135,  0.26978666,  0.17679983,  0.42649922,
        0.77873451,  0.85414308,  0.75050647,  0.56839475,  0.00953569,
        0.56640128, -0.31674518, -0.75834679,  0.93474574, -0.31

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [80]:
def distance(P0,P1,p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[4.18642895 1.93103762 0.9230596  4.61177815 7.23353607 4.14686642
 5.09577346 1.63426136 2.32393071 0.20890076]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [81]:
def distance(P0,P1,p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.88100176  8.96163718  7.88115083  9.33977878  0.45732617  2.08830652
   2.39491986 11.09690673  0.41770941  8.80341792]
 [ 2.74990806  8.83900266 12.36839831 11.86283771  4.03981189  6.70849147
   6.11364218 11.59403691  4.23993929  5.87381534]
 [ 0.11005035  0.08513451  8.21951326  3.37265061  3.04911711  6.27432313
   0.69735455  2.48679642  1.89129554  0.02047677]
 [ 1.62734933  2.49234109  8.58009164  5.33817503  1.68005391  5.54691846
   0.56702578  5.00244254  1.705075    2.2070388 ]
 [10.32020442  6.75004225  2.31026009  4.59689869  4.97810689  2.64385901
   3.10400754  8.21786675  5.68807396 10.19031408]
 [13.4793451   7.2131011   0.82833411  3.08919867  7.32620971  6.03564251
   5.56426183  8.2311547   9.02758533 12.59855953]
 [ 5.45019226  5.18108164  1.74878715  5.88980053 13.2508394   1.70970519
  10.96180475  3.75432056  7.29259854  1.37730008]
 [ 5.75583955  6.97101606  9.26746094  0.71004241  5.07795648 10.26512712
   2.38792044  3.95848726  4.4645186   7.23218886]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape,dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start,(R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [83]:
Z = np.arange(1,15,dtype = uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [84]:
Z = np.random.uniform(0,1,(10,10))
U,S,V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [85]:
x = np.random.randint(0,10,20)
print(np.bincount(x).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [86]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z,shape=(i,j,n,n), strides=Z.strides+Z.strides)
print(C)

[[[[2 4 3]
   [4 4 1]
   [0 3 0]]

  [[4 3 3]
   [4 1 3]
   [3 0 3]]

  [[3 3 0]
   [1 3 1]
   [0 3 3]]

  [[3 0 0]
   [3 1 4]
   [3 3 2]]

  [[0 0 3]
   [1 4 4]
   [3 2 3]]

  [[0 3 3]
   [4 4 3]
   [2 3 3]]

  [[3 3 4]
   [4 3 4]
   [3 3 0]]

  [[3 4 4]
   [3 4 4]
   [3 0 2]]]


 [[[4 4 1]
   [0 3 0]
   [3 3 2]]

  [[4 1 3]
   [3 0 3]
   [3 2 2]]

  [[1 3 1]
   [0 3 3]
   [2 2 3]]

  [[3 1 4]
   [3 3 2]
   [2 3 1]]

  [[1 4 4]
   [3 2 3]
   [3 1 2]]

  [[4 4 3]
   [2 3 3]
   [1 2 3]]

  [[4 3 4]
   [3 3 0]
   [2 3 3]]

  [[3 4 4]
   [3 0 2]
   [3 3 0]]]


 [[[0 3 0]
   [3 3 2]
   [0 0 0]]

  [[3 0 3]
   [3 2 2]
   [0 0 0]]

  [[0 3 3]
   [2 2 3]
   [0 0 1]]

  [[3 3 2]
   [2 3 1]
   [0 1 3]]

  [[3 2 3]
   [3 1 2]
   [1 3 2]]

  [[2 3 3]
   [1 2 3]
   [3 2 2]]

  [[3 3 0]
   [2 3 3]
   [2 2 3]]

  [[3 0 2]
   [3 3 0]
   [2 3 3]]]


 [[[3 3 2]
   [0 0 0]
   [4 0 0]]

  [[3 2 2]
   [0 0 0]
   [0 0 0]]

  [[2 2 3]
   [0 0 1]
   [0 0 4]]

  [[2 3 1]
   [0 1 3]
   [0 4 4]]

  [[3 1 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [87]:
class Symetric(np.ndarray):
    def __setitem__(self,index,value):
        i,j = index
        super(Symetric,self).__setitem__((i,j),value)
        super(Symetric,self).__setitem__((j,i),value)
        
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  8  7 13  7]
 [ 8  0 12  6  3]
 [ 7 12  7 42 15]
 [13  6 42  9  8]
 [ 7  3 15  8  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [88]:
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V, axes=[[0,2] , [0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [89]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k), axis=0),np.arange(0,Z.shape[1],k),axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] + 
         Z[1:-1,0:-2]                + Z[1:-1,2:] + 
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    z[...] = 0
    z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

In [91]:
X = np.arange(1000)
np.random.shuffle(X)
n = 5
print(X[np.argsort(X)[-n:]])
print(X[np.argpartition(-X,n)[:n]])

[995 996 997 998 999]
[999 997 998 996 995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape,dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n,arr in enumerate(arrays):
        ix[:,n] = arrays[n][ix[:,n]]
    return ix

print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [93]:
Z = np.array([("Hello",3.5,4),("World",3.6,2)])
R = np.core.records.fromarrays(Z.T,names='col1,col2,col3', formats = 'S8,f8,i8')
print(R)

[(b'Hello', 3.5, 4) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [94]:
x = np.random.rand(5e7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [95]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[...,np.newaxis,np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [96]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1] , axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 2 0]
 [3 0 2]
 [2 4 1]
 [2 0 0]
 [3 1 4]
 [1 1 0]
 [1 3 1]
 [4 3 3]
 [2 3 1]
 [3 2 3]]
[[0 2 0]
 [3 0 2]
 [2 4 1]
 [2 0 0]
 [3 1 4]
 [1 1 0]
 [1 3 1]
 [4 3 3]
 [2 3 1]
 [3 2 3]]
[[0 2 0]
 [3 0 2]
 [2 4 1]
 [2 0 0]
 [3 1 4]
 [1 1 0]
 [1 3 1]
 [4 3 3]
 [2 3 1]
 [3 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [97]:
I = np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [98]:
X = np.random.randint(0,2,(6,3))
Y = np.ascontiguousarray(X).view(np.dtype((np.void, X.dtype.itemsize * X.shape[1])))
_, idx = np.unique(Y,return_index=True)
uX = X[idx]
print(uX)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [99]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)
np.einsum('i,i->', A,B)
np.einsum('i,i', A,B)
np.einsum('i,j->ij', A,B)

array([[0.01153147, 0.26218482, 0.56545719, 0.60340584, 0.50867205,
        0.28526614, 0.38617107, 0.27051181, 0.5999154 , 0.11938749],
       [0.01469169, 0.33403705, 0.72042175, 0.7687703 , 0.64807454,
        0.36344384, 0.49200195, 0.34464606, 0.76432329, 0.15210585],
       [0.00637309, 0.14490164, 0.31251112, 0.3334842 , 0.28112769,
        0.15765799, 0.2134251 , 0.14950371, 0.33155514, 0.06598187],
       [0.01508304, 0.34293501, 0.73961209, 0.78924852, 0.66533772,
        0.37312513, 0.50510773, 0.35382662, 0.78468307, 0.15615759],
       [0.00254397, 0.05784087, 0.1247461 , 0.13311799, 0.11221867,
        0.06293286, 0.0851936 , 0.05967789, 0.13234796, 0.0263382 ],
       [0.01626194, 0.36973916, 0.79742094, 0.85093701, 0.71734121,
        0.40228898, 0.54458747, 0.38148207, 0.84601471, 0.16836303],
       [0.00968672, 0.2202417 , 0.47499795, 0.50687575, 0.42729704,
        0.23963058, 0.32439321, 0.22723658, 0.5039437 , 0.10028843],
       [0.00269487, 0.06127183, 0.1321457

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [100]:
phi = np.arange(0,10*np.pi,0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0,r.max(),200)
x_int = np.interp(r_int,r,x)
y_int = np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [101]:
X = np.asarray([[1.0,0.0,3.0,8.0],[2.0,0.0,1.0,1.0],[1.5,2.5,1.0,0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X,1) == 0,axis=-1)
M &= (X.sum(axis=1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [102]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0,X.size,(N,X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[-0.38672961  0.02763955]
